# Generated by Django 3.0.6 on 2020-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
