# Generated by Django 3.0.6 on 2020-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_shippingaddress_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default='tree', max_length=200),
            preserve_default=False,
        ),
    ]
